version: "3.7"

services:
  club_app: &app
    image: ghcr.io/umag/vas3k.club:latest
    command: make docker-run-production
    container_name: club_app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://vas3k.club
      - MEDIA_UPLOAD_URL=https://i.vas3k.club/upload/
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=vas3k
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - PUID=1000
      - PGID=1000
    restart: always
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "8814:8814"

  queue:
    <<: *app
    environment:
      - PUID=1000
      - PGID=1000
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: vas3k
      POSTGRES_DB: vas3k_club
      PUID: 1000
      PGID: 1000
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw
    ports:
      - "54333:5432"

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PUID=1000
      - PGID=1000
